baseURL = "https://Saroj-VC.github.io/Pulses/"
languageCode = "en-us"
title = "Agri-food Value Chain Management"
theme = "hugo-theme-cleanwhite"
publishDir = "public"

relativeURLs = false
canonifyURLs = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  header_image = "img/home-bg.jpg"
  slogan = "Developing competitive and inclusive value chains of pulses in Pakistan"
  search = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = ""
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About Us"
    url = "about-us/"
    weight = 10

  [[menu.main]]
    identifier = "project"
    name = "Project"
    url = "project/"
    weight = 20

  [[menu.main]]
    identifier = "publication"
    name = "Publication"
    url = "publication/"
    weight = 30

  [[menu.main]]
    identifier = "gallery"
    name = "Gallery"
    url = "gallery/"
    weight = 40

  [[menu.main]]
    identifier = "event"
    name = "Event"
    url = "event/"
    weight = 50

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "contact/"
    weight = 60

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true